<template>
  <header class="py-6 px-6">
    <div class="flex justify-start items-center">
      <nav>
        <ul class="flex list-none m-0 p-0 gap-4 items-center">
          <li>
            <NuxtLink to="/">
              <img
                src="/digigarden2025.png"
                alt="home"
                class="h-6"
              >
            </NuxtLink>
          </li>
          <li>
            <NuxtLink
              to="/about"
              class="text-sm"
            >about</NuxtLink>
          </li>
          <li>
            <NuxtLink
              to="/use"
              class="text-sm"
            >use</NuxtLink>
          </li>
          <li>
            <NuxtLink
              to="/blog"
              class="text-sm"
            >blog</NuxtLink>
          </li>
          <li>
            <NuxtLink
              to="/project"
              class="text-sm"
            >project</NuxtLink>
          </li>
          <li>
            <NuxtLink
              to="/contact"
              class="text-sm"
            >contact</NuxtLink>
          </li>
        </ul>
      </nav>
    </div>
  </header>
</template>
